### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by rondagdag** [googlecodelabs/androidthings-googleassistant#1]
I get this error compiling
when I run this command 

./gradlew assembleDebug

Here's the error. credentials.json exist

> Task :step1-start-here:compileDebugJavaWithJavac
/Users/Ron/Downloads/androidthings-googleassistant/step1-start-here/src/main/java/com/example/androidthings/assistant/AssistantActivity.java:337: error: cannot access UserCredentials
                    .withCallCredentials(MoreCallCredentials.from(
                                                                 ^
  class file for com.google.auth.oauth2.UserCredentials not found
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':step1-start-here:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by Fleker** [comment]
Did you follow the steps [in the codelab](https://codelabs.developers.google.com/codelabs/androidthings-assistant/#2) to use the `google-oauthlib-tool`?
