### ISSUE TITLE
error: cannot find symbol variable raw

### ISSUE THREAD

**Issue by Sidelaunch** [googlecodelabs/androidthings-googleassistant#14]
Tried cleaning and rebuilding but the error persists

**Comment by Fleker** [comment]
You need to generate this file.

On https://codelabs.developers.google.com/codelabs/androidthings-assistant/#2
```
google-oauthlib-tool --client-secrets path/to/credentials.json \
                       --credentials shared/src/main/res/raw/credentials.json \
                       --scope https://www.googleapis.com/auth/assistant-sdk-prototype \
                       --save
````

This generates the file and saves it in your project

**Comment by Sidelaunch** [comment]
Ahhh of course! Im rebuilding the project on a new machine and completely forgot about that... Thanks so much for the help.
