### ISSUE TITLE
androidthings-peripherals: Broken link in documentation

### ISSUE THREAD

**Issue by Farbklex** [googlecodelabs/androidthings-googleassistant#15]
First: It seems like issue submission is disabled for the androidthings-peripherals and androidthings-weatherstation repositories. Is this intended?

I found a broken link in the [androidthings-peripherals](https://github.com/googlecodelabs/androidthings-peripherals) codelab:
Step 10.: Link to the Simple PIO Blink project is broken. I think the right one is https://github.com/androidthings/sample-simplepio/tree/master/java/blink instead of https://github.com/androidthings/sample-simplepio/tree/master/blink

**Comment by Fleker** [comment]
I don't think it's intentional if the codelab's bug link is to GitHub. I'll pass this along, thanks.

**Comment by devunwired** [comment]
Both issues are now fixed.
