### ISSUE TITLE
Google Assistant not responding

### ISSUE THREAD

**Issue by aabedraba** [googlecodelabs/androidthings-googleassistant#6]
I am using VoiceHat + Pico Pro iMX7.d and changed all the pins to correctly correspond the ones in th Pico Pro. Everything is correct as far as I know, but Google Assistant does not respond.
When I disable any Activity Control (such as Device Control) it answers: "Give me permission to help you". But as soon as I enable it again and try with any phrase it won't respond.

**Comment by Fleker** [comment]
Do you see the LED turn on and off if you push the button? If not, there may be a hardware connection issue.

The imx7.d does not have I2S pins on the board by default, so you will not be able to get any audio input/output using the VoiceHat. If you do want to use the imx7.d you will need to attach an external audio input and output.

**Comment by aabedraba** [comment]
You're probably correct. The only way output worked was with the default audio-jack integrated with the board. Will leave trying for now with the imx7.d. Thanks for your answer :)
